import { useState } from "react";
import { initialWorkouts, generateWorkout } from "./Workouts.js";
import "./App.css";

function App() {
  const [workouts, setWorkouts] = useState(initialWorkouts);

  const addNewWorkout = () => {
    const newWorkout = generateWorkout(); // this variable is storing a new workout array which is generated by the generateWorkout()
    console.log("addNewWorkout:", newWorkout);
    const mondayWorkoutArr = [...workouts]; // This [...workouts] is looping into the old arr and assigning it into the var
    mondayWorkoutArr.push(newWorkout); // now the new arr is being pushed into the old arr which replaces the previous value of the arr
    setWorkouts(mondayWorkoutArr); // setting the state to the newly created array.
  };

  const deleteWorkout = (workout) => {
    console.log("deleteWorkout:", workout);
    const deletedItem = workouts.filter(function (item) {
      return item !== workout;
    });
    setWorkouts(deletedItem);
  };

  const completeWorkout = (target) => {
    console.log("completeWorkout:", target);
    const updateWorkOut = workouts.map((item) => {
      if (item === target) {
        return { ...item, done: !item.done };
      }
      return item;
    });
    setWorkouts(updateWorkOut);
  };

  return (
    <div className="App">
      <h1>🏋️‍♀️Workout Generator</h1>
      <button onClick={addNewWorkout}>Add New Workout</button>
      <ul>
        {workouts.map((workout, index) => (
          <li key={index}>
            <p>
              {workout.sets}x sets of{" "}
              <strong>
                {workout.reps}x{workout.exercise}
              </strong>{" "}
              with {workout.rest} seconds rest
            </p>
            {!workout.done && (
              <button onClick={(e) => completeWorkout(workout)}>Done</button>
            )}
            {workout.done && <p>✅</p>}
            <button onClick={(e) => deleteWorkout(workout)}>Delete</button>
          </li>
        ))}
      </ul>
    </div>
  );
}

export default App;
